ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY),y)
dtbo-$(CONFIG_ARCH_ZQL1695) += samsung-sdm439-qrd-r00-default-overlay.dtbo \
	samsung-sdm439-qrd-r01-overlay.dtbo \
	samsung-sdm439-qrd-r02-overlay.dtbo \
	samsung-sdm439-qrd-r03-overlay.dtbo \
	samsung-sdm439-qrd-r04-overlay.dtbo \
	samsung-sdm439-qrd-r05-overlay.dtbo \
	samsung-sdm439-qrd-r06-overlay.dtbo \
	samsung-sdm439-qrd-r07-overlay.dtbo \
	samsung-sdm439-qrd-r08-overlay.dtbo \
	samsung-sdm439-qrd-r09-overlay.dtbo

samsung-sdm439-qrd-r01-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r02-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r03-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r04-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r05-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r06-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r07-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r08-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r09-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb

# HS70 code added by tangqingyong for HS70-9 at 20191002 start
# HS70 code added by tangqingyong for HS70-11 at 20191003 start
dtbo-$(CONFIG_ARCH_ZQL1871) += samsung-sdm450-qrd-r00-default-overlay.dtbo \
	samsung-sdm450-qrd-r01-overlay.dtbo \
	samsung-sdm450-qrd-r02-overlay.dtbo \
	samsung-sdm450-qrd-r03-overlay.dtbo \
	samsung-sdm450-qrd-r04-overlay.dtbo \
	samsung-sdm450-qrd-r05-overlay.dtbo \
	samsung-sdm450-qrd-r06-overlay.dtbo \
	samsung-sdm450-qrd-r07-overlay.dtbo \
	samsung-sdm450-qrd-r08-overlay.dtbo \
	samsung-sdm450-qrd-r09-overlay.dtbo

samsung-sdm450-qrd-r00-default-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r01-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r02-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r03-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r04-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r05-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r06-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r07-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r08-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r09-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
# HS70 code added by tangqingyong for HS70-11 at 20191003 end
# HS70 code added by tangqingyong for HS70-9 at 20191002 end
# HS50 code added by xudayi for SR-QL3095-01-139 at 20200714 start
dtbo-$(CONFIG_ARCH_HS50) += samsung-sdm450-qrd-hs50-r00-default-overlay.dtbo \
	samsung-sdm450-qrd-hs50-r01-overlay.dtbo \
	samsung-sdm450-qrd-hs50-r02-overlay.dtbo \
	samsung-sdm450-qrd-hs50-r03-overlay.dtbo \
	samsung-sdm450-qrd-hs50-r04-overlay.dtbo \
	samsung-sdm450-qrd-hs50-r05-overlay.dtbo \
	samsung-sdm450-qrd-hs50-r06-overlay.dtbo \
	samsung-sdm450-qrd-hs50-r07-overlay.dtbo \
	samsung-sdm450-qrd-hs50-r08-overlay.dtbo \
	samsung-sdm450-qrd-hs50-r09-overlay.dtbo

samsung-sdm450-qrd-hs50-r00-default-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-hs50-r01-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-hs50-r02-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-hs50-r03-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-hs50-r04-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-hs50-r05-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-hs50-r06-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-hs50-r07-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-hs50-r08-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-hs50-r09-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
